# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sidehelm VR Demos
email: iamwil+sidehelm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  VR experiments with different mechanics
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iamwilhelm.github.io/blog.sidehelm.com" # the base hostname & protocol for your site
twitter_username: iamwil
github_username:  iamwilhelm
gems:
  - jekyll-youtube

# Build settings
markdown: kramdown
